/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package znn.installer;

import java.awt.Frame;
import javax.swing.JDialog;

/**
 *
 * @author Edgar Mesquita
 */
public class ChooseFolderFrame extends JDialog
{
    private Frame _owner;
    /**
     * Creates new form ChooseFolderFrame
     */
    public ChooseFolderFrame(Frame owner)
    {
        super(owner);
        _owner = owner;
        this.setLocationRelativeTo(owner);
        initComponents();
    }

    @Override
    public void setVisible(boolean visible)
    {
        super.setVisible(visible);
        _owner.setEnabled(!visible);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jFileChooser1 = new javax.swing.JFileChooser();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Selecione o destino");
        setMinimumSize(new java.awt.Dimension(740, 460));
        setPreferredSize(new java.awt.Dimension(740, 460));
        setType(java.awt.Window.Type.POPUP);

        jFileChooser1.setFileSelectionMode(javax.swing.JFileChooser.DIRECTORIES_ONLY);
        jFileChooser1.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jFileChooser1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jFileChooser1, javax.swing.GroupLayout.DEFAULT_SIZE, 700, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jFileChooser1, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );

        getAccessibleContext().setAccessibleParent(this);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jFileChooser1ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jFileChooser1ActionPerformed
    {//GEN-HEADEREND:event_jFileChooser1ActionPerformed
        MainFrame mainFrame = (MainFrame)_owner;
        
        if("ApproveSelection".equals(evt.getActionCommand()))
        {
            mainFrame.setInstallPath(jFileChooser1.getSelectedFile().getAbsolutePath());
            this.dispose();
        }
        else if("CancelSelection".equals(evt.getActionCommand()))
        {
            this.dispose();
        }
    }//GEN-LAST:event_jFileChooser1ActionPerformed

    @Override
    public void dispose()
    {
        _owner.setEnabled(true);
        super.dispose();
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFileChooser jFileChooser1;
    // End of variables declaration//GEN-END:variables
}
